apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader-yusuf-role
  namespace: default
rules:
  - apiGroups: ["","apps"]
    resources: ["pods"]
    verbs: ["get","watch", "list"]
