apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-yusuf-binding
  namespace: default
subjects:
  - kind: User
    name: yusuf
    apiGroup: rbac.authorization.k8s.io
roleRef:
   kind: Role
   name: pod-reader-yusuf-role
   apiGroup: rbac.authorization.k8s.io
